
def make_str(filename):
	my_list = []
	with open(filename) as inp:
		my_ln = inp.read()
		my_list.append(my_ln)
	return my_list


nl_scores = ['Rikers Island|32', 'Clinton|31', 'Woodside|30', 'Upper East Side-Carnegie Hill|30', 'Stuyvesant Town-Cooper Village|30', 'Turtle Bay-East Midtown|29', 'Queensbridge-Ravenswood-Long Island City|29', 'Battery Park City-Lower Manhattan|29', 'West Village|28', 'Midtown-Midtown South|28', 'Hudson Yards-Chelsea-Flat Iron-Union Square|28', 'Greenpoint|28', 'Upper West Side|28', 'Hamilton Heights|28', 'East Harlem South|28', 'East Williamsburg|27', 'SoHo-TriBeCa-Civic Center-Little Italy|27', 'Mount Hope|27', 'Yorkville|27', 'Washington Heights North|27', 'Washington Heights South|26', 'Lower East Side|26', 'Bedford|26', 'Murray Hill|26', 'Williamsbridge-Olinville|26', 'East Village|26', 'Flushing|26', 'Central Harlem South|26', 'Forest Hills|26', 'Briarwood-Jamaica Hills|26', 'Murray Hill-Kips Bay|26', 'Ocean Parkway South|26', 'Borough Park|26', 'Bushwick South|25', 'Prospect Lefferts Gardens-Wingate|25', 'Lincoln Square|25', 'Prospect Heights|25', 'Astoria|25', 'Crown Heights North|25', 'Crown Heights South|25', 'Bushwick North|25', 'DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum H|24', 'Elmhurst-Maspeth|24', 'Chinatown|24', 'Lenox Hill-Roosevelt Island|24', 'Steinway|24', 'Mott Haven-Port Morris|24', 'Ridgewood|24', 'Manhattanville|24', 'Ocean Hill|24', 'Elmhurst|24', 'Flatbush|24', 'Jackson Heights|24', 'Rugby-Remsen Village|23', 'Sunset Park West|23', 'Sunset Park East|23', 'East Elmhurst|23', 'Melrose South-Mott Haven North|23', 'Pomonok-Flushing Heights-Hillcrest|23', 'Middle Village|23', 'Williamsburg|23', 'Bensonhurst West|22', 'Brooklyn Heights-Cobble Hill|22', 'Fordham South|22', 'Midwood|22', 'Rosedale|22', 'Bay Ridge|22', 'Clinton Hill|22', 'Gravesend|22', 'Rego Park|22', 'Maspeth|22', 'University Heights-Morris Heights|22', 'Brownsville|22', 'East Tremont|22', 'Fort Greene|22', 'Crotona Park East|22', 'Dyker Heights|22', 'Auburndale|22', 'Bensonhurst East|22', 'Madison|22', 'Glendale|21', 'Bronxdale|21', 'Bedford Park-Fordham North|21', 'Hunters Point-Sunnyside-West Maspeth|21', 'Norwood|21', 'Carroll Gardens-Columbia Street-Red Hook|21', 'Cypress Hills-City Line|21', "Mariner's Harbor-Arlington-Port Ivory-Granite|21", 'North Corona|21', 'Soundview-Castle Hill-Clason Point-Harding Pa|21', 'Jamaica|20', 'Bath Beach|20', 'Richmond Hill|20', 'Corona|20', 'East Flushing|20', 'Breezy Point-Belle Harbor-Rockaway Park-Broad|20', 'Jamaica Estates-Holliswood|20', 'College Point|20', 'Erasmus|20', 'Brighton Beach|20', 'Flatlands|20', 'Highbridge|20', 'Morningside Heights|20', 'Central Harlem North-Polo Grounds|20', 'South Jamaica|20', 'Stuyvesant Heights|20', 'Windsor Terrace|20', 'Seagate-Coney Island|20', 'East Harlem North|20', 'Fresh Meadows-Utopia|20', 'Bellerose|19', 'East Concourse-Concourse Village|19', 'South Ozone Park|19', 'Kensington-Ocean Parkway|19', 'Whitestone|19', 'Queensboro Hill|19', 'East New York|19', 'Co-Op City|19', 'Ozone Park|19', 'Gramercy|19', 'Homecrest|19', 'Baisley Park|19', 'West New Brighton-New Brighton-St. George|19', 'Belmont|19', 'St. Albans|19', 'Kew Gardens Hills|18', 'East Flatbush-Farragut|18', 'Sheepshead Bay-Gerritsen Beach-Manhattan Beac|18', 'Westerleigh|18', 'Kew Gardens|18', 'Claremont-Bathgate|18', 'Parkchester|18', 'Queens Village|18', 'Morrisania-Melrose|18', 'Todt Hill-Emerson Hill-Heartland Village-Ligh|18', 'West Brighton|18', 'Marble Hill-Inwood|18', 'Spuyten Duyvil-Kingsbridge|18', 'Canarsie|18', 'East New York (Pennsylvania Ave)|18', 'Lindenwood-Howard Beach|18', 'Westchester-Unionport|18', 'Oakland Gardens|18', 'Kingsbridge Heights|18', 'West Farms-Bronx River|18', 'Bayside-Bayside Hills|17', 'Woodhaven|17', 'West Concourse|17', 'Longwood|17', 'Van Cortlandt Village|17', 'Pelham Parkway|16', 'Woodlawn-Wakefield|16', 'Grymes Hill-Clifton-Fox Hills|16', 'Port Richmond|16', 'Laurelton|16', 'Far Rockaway-Bayswater|16', 'Georgetown-Marine Park-Bergen Beach-Mill Basi|16', 'Great Kills|16', 'Soundview-Bruckner|16', 'Cambria Heights|15', 'Glen Oaks-Floral Park-New Hyde Park|15', 'Oakwood-Oakwood Beach|15', 'Douglas Manor-Douglaston-Little Neck|15', 'Van Nest-Morris Park-Westchester Square|15', 'New Dorp-Midland Beach|14', 'Old Town-Dongan Hills-South Beach|14', 'Old Astoria|14', 'North Riverdale-Fieldston-Riverdale|14', 'Hollis|14', 'Springfield Gardens North|14', 'Hunts Point|14', 'Schuylerville-Throgs Neck-Edgewater Park|14', 'Eastchester-Edenwald-Baychester|14', 'Stapleton-Rosebank|14', 'New Springville-Bloomfield-Travis|13', 'Grasmere-Arrochar-Ft. Wadsworth|13', 'North Side-South Side|12', 'Springfield Gardens South-Brookville|12', 'Allerton-Pelham Gardens|12', 'Charleston-Richmond Valley-Tottenville|12', 'Rossville-Woodrow|12', 'Arden Heights|11', 'Pelham Bay-Country Club-City Island|11', 'Starrett City|11', 'Hammels-Arverne-Edgemere|10', "Annadale-Huguenot-Prince's Bay-Eltingville|10", 'Ft. Totten-Bay Terrace-Clearview|10', 'New Brighton-Silver Lake|9', 'Park Slope-Gowanus|0']




def split_pipes(my_list):
	my_dict = {}
	for el in my_list:
		splitter = el.split('|')
		my_dict[splitter[0]] = int(splitter[1])
	return my_dict

split_dict = {'Allerton-Pelham Gardens': 12,
 "Annadale-Huguenot-Prince's Bay-Eltingville": 10,
 'Arden Heights': 11,
 'Astoria': 25,
 'Auburndale': 22,
 'Baisley Park': 19,
 'Bath Beach': 20,
 'Battery Park City-Lower Manhattan': 29,
 'Bay Ridge': 22,
 'Bayside-Bayside Hills': 17,
 'Bedford': 26,
 'Bedford Park-Fordham North': 21,
 'Bellerose': 19,
 'Belmont': 19,
 'Bensonhurst East': 22,
 'Bensonhurst West': 22,
 'Borough Park': 26,
 'Breezy Point-Belle Harbor-Rockaway Park-Broad': 20,
 'Briarwood-Jamaica Hills': 26,
 'Brighton Beach': 20,
 'Bronxdale': 21,
 'Brooklyn Heights-Cobble Hill': 22,
 'Brownsville': 22,
 'Bushwick North': 25,
 'Bushwick South': 25,
 'Cambria Heights': 15,
 'Canarsie': 18,
 'Carroll Gardens-Columbia Street-Red Hook': 21,
 'Central Harlem North-Polo Grounds': 20,
 'Central Harlem South': 26,
 'Charleston-Richmond Valley-Tottenville': 12,
 'Chinatown': 24,
 'Claremont-Bathgate': 18,
 'Clinton': 31,
 'Clinton Hill': 22,
 'Co-Op City': 19,
 'College Point': 20,
 'Corona': 20,
 'Crotona Park East': 22,
 'Crown Heights North': 25,
 'Crown Heights South': 25,
 'Cypress Hills-City Line': 21,
 'DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum H': 24,
 'Douglas Manor-Douglaston-Little Neck': 15,
 'Dyker Heights': 22,
 'East Concourse-Concourse Village': 19,
 'East Elmhurst': 23,
 'East Flatbush-Farragut': 18,
 'East Flushing': 20,
 'East Harlem North': 20,
 'East Harlem South': 28,
 'East New York': 19,
 'East New York (Pennsylvania Ave)': 18,
 'East Tremont': 22,
 'East Village': 26,
 'East Williamsburg': 27,
 'Eastchester-Edenwald-Baychester': 14,
 'Elmhurst': 24,
 'Elmhurst-Maspeth': 24,
 'Erasmus': 20,
 'Far Rockaway-Bayswater': 16,
 'Flatbush': 24,
 'Flatlands': 20,
 'Flushing': 26,
 'Fordham South': 22,
 'Forest Hills': 26,
 'Fort Greene': 22,
 'Fresh Meadows-Utopia': 20,
 'Ft. Totten-Bay Terrace-Clearview': 10,
 'Georgetown-Marine Park-Bergen Beach-Mill Basi': 16,
 'Glen Oaks-Floral Park-New Hyde Park': 15,
 'Glendale': 21,
 'Gramercy': 19,
 'Grasmere-Arrochar-Ft. Wadsworth': 13,
 'Gravesend': 22,
 'Great Kills': 16,
 'Greenpoint': 28,
 'Grymes Hill-Clifton-Fox Hills': 16,
 'Hamilton Heights': 28,
 'Hammels-Arverne-Edgemere': 10,
 'Highbridge': 20,
 'Hollis': 14,
 'Homecrest': 19,
 'Hudson Yards-Chelsea-Flat Iron-Union Square': 28,
 'Hunters Point-Sunnyside-West Maspeth': 21,
 'Hunts Point': 14,
 'Jackson Heights': 24,
 'Jamaica': 20,
 'Jamaica Estates-Holliswood': 20,
 'Kensington-Ocean Parkway': 19,
 'Kew Gardens': 18,
 'Kew Gardens Hills': 18,
 'Kingsbridge Heights': 18,
 'Laurelton': 16,
 'Lenox Hill-Roosevelt Island': 24,
 'Lincoln Square': 25,
 'Lindenwood-Howard Beach': 18,
 'Longwood': 17,
 'Lower East Side': 26,
 'Madison': 22,
 'Manhattanville': 24,
 'Marble Hill-Inwood': 18,
 "Mariner's Harbor-Arlington-Port Ivory-Granite": 21,
 'Maspeth': 22,
 'Melrose South-Mott Haven North': 23,
 'Middle Village': 23,
 'Midtown-Midtown South': 28,
 'Midwood': 22,
 'Morningside Heights': 20,
 'Morrisania-Melrose': 18,
 'Mott Haven-Port Morris': 24,
 'Mount Hope': 27,
 'Murray Hill': 26,
 'Murray Hill-Kips Bay': 26,
 'New Brighton-Silver Lake': 9,
 'New Dorp-Midland Beach': 14,
 'New Springville-Bloomfield-Travis': 13,
 'North Corona': 21,
 'North Riverdale-Fieldston-Riverdale': 14,
 'North Side-South Side': 12,
 'Norwood': 21,
 'Oakland Gardens': 18,
 'Oakwood-Oakwood Beach': 15,
 'Ocean Hill': 24,
 'Ocean Parkway South': 26,
 'Old Astoria': 14,
 'Old Town-Dongan Hills-South Beach': 14,
 'Ozone Park': 19,
 'Park Slope-Gowanus': 0,
 'Parkchester': 18,
 'Pelham Bay-Country Club-City Island': 11,
 'Pelham Parkway': 16,
 'Pomonok-Flushing Heights-Hillcrest': 23,
 'Port Richmond': 16,
 'Prospect Heights': 25,
 'Prospect Lefferts Gardens-Wingate': 25,
 'Queens Village': 18,
 'Queensboro Hill': 19,
 'Queensbridge-Ravenswood-Long Island City': 29,
 'Rego Park': 22,
 'Richmond Hill': 20,
 'Ridgewood': 24,
 'Rikers Island': 32,
 'Rosedale': 22,
 'Rossville-Woodrow': 12,
 'Rugby-Remsen Village': 23,
 'Schuylerville-Throgs Neck-Edgewater Park': 14,
 'Seagate-Coney Island': 20,
 'Sheepshead Bay-Gerritsen Beach-Manhattan Beac': 18,
 'SoHo-TriBeCa-Civic Center-Little Italy': 27,
 'Soundview-Bruckner': 16,
 'Soundview-Castle Hill-Clason Point-Harding Pa': 21,
 'South Jamaica': 20,
 'South Ozone Park': 19,
 'Springfield Gardens North': 14,
 'Springfield Gardens South-Brookville': 12,
 'Spuyten Duyvil-Kingsbridge': 18,
 'St. Albans': 19,
 'Stapleton-Rosebank': 14,
 'Starrett City': 11,
 'Steinway': 24,
 'Stuyvesant Heights': 20,
 'Stuyvesant Town-Cooper Village': 30,
 'Sunset Park East': 23,
 'Sunset Park West': 23,
 'Todt Hill-Emerson Hill-Heartland Village-Ligh': 18,
 'Turtle Bay-East Midtown': 29,
 'University Heights-Morris Heights': 22,
 'Upper East Side-Carnegie Hill': 30,
 'Upper West Side': 28,
 'Van Cortlandt Village': 17,
 'Van Nest-Morris Park-Westchester Square': 15,
 'Washington Heights North': 27,
 'Washington Heights South': 26,
 'West Brighton': 18,
 'West Concourse': 17,
 'West Farms-Bronx River': 18,
 'West New Brighton-New Brighton-St. George': 19,
 'West Village': 28,
 'Westchester-Unionport': 18,
 'Westerleigh': 18,
 'Whitestone': 19,
 'Williamsbridge-Olinville': 26,
 'Williamsburg': 23,
 'Windsor Terrace': 20,
 'Woodhaven': 17,
 'Woodlawn-Wakefield': 16,
 'Woodside': 30,
 'Yorkville': 27}