# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_0_19', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_20_24', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_25_34', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_35_64', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_65_over', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_median', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units_2_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_units_3_10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_units_10_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('constucted_before_1970', models.DecimalField(decimal_places=2, max_digits=10)),
                ('constucted_1970_2000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('constucted_after_2000', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divorced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_yr_turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birth_native', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birth_foreign', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender_f', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laborforce', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unemployed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('below_poverty_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_0_50', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_50_100', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_100_200', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_200_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mean_income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_school_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elem_school_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hs_school_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_enrollment_pre_highschool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_enrollment_highschool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_enrollment_college', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_highschool_over', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_college_over', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_life_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commute_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crime_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noise_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_occupied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_vacant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_per_unit_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_per_unit_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_per_unit_3_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_per_unit_6_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resident_type_owner', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resident_type_renter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_residence_before_2000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_residence_2000_2009', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_residence_after_2010', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicles_0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicles_1_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='UnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_of_unit_500_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_of_unit_500_1M', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_of_unit_1M_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_of_unit_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_1000_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_1000_1500', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_1500_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='economic',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood'),
        ),
        migrations.AddField(
            model_name='building',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood'),
        ),
        migrations.AddField(
            model_name='ages',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood'),
        ),
    ]
