# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetEasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('squarefeet_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('squarefeet_average', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='pic_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='webdisplay',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='streeteasy',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood'),
        ),
    ]
