# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='latutude',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='pic_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
