# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_0_19', models.DecimalField(decimal_places=5, max_digits=10)),
                ('age_20_24', models.DecimalField(decimal_places=5, max_digits=10)),
                ('age_25_34', models.DecimalField(decimal_places=5, max_digits=10)),
                ('age_35_64', models.DecimalField(decimal_places=5, max_digits=10)),
                ('age_65_over', models.DecimalField(decimal_places=5, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
    ]
