# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20160428_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='latutude',
            new_name='latitude',
        ),
    ]
