# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ages',
            name='age_median',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
