# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20160503_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='borough',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
