# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_ages_age_median'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units_2_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_units_3_10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_units_10_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('constucted_before_1970', models.DecimalField(decimal_places=2, max_digits=10)),
                ('constucted_1970_2000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('constucted_after_2000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='UnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_of_unit_500_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_of_unit_500_1M', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_of_unit_1M_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_of_unit_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_1000_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_1000_1500', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_1500_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_rent_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.AlterField(
            model_name='ages',
            name='age_0_19',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ages',
            name='age_20_24',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ages',
            name='age_25_34',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ages',
            name='age_35_64',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ages',
            name='age_65_over',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ages',
            name='age_median',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='below_poverty_level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='income_0_50',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='income_100_200',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='income_200_plus',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='income_50_100',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='laborforce',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='mean_income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='median_income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='economic',
            name='unemployed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
