# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_ages_age_median'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divorced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_yr_turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birth_native', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birth_foreign', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender_f', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_enrollment_pre_highschool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_enrollment_highschool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_enrollment_college', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_highschool_over', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_college_over', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
    ]
