# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20160429_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='webdisplay',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
