# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_neighborhood_webdisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetEasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('squarefeet_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('squarefeet_average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
    ]
