# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20160418_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
