# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_demographic_schooleducation'),
        ('tables', '0005_auto_20160418_1825'),
    ]

    operations = [
    ]
