# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_occupied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_vacant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_per_unit_under_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_per_unit_over_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resident_type_owner', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resident_type_renter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_residence_before_2000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_residence_2000_2009', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_residence_after_2010', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicles_0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicles_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicles_2_plus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
    ]
