# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_unitdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitdescription',
            old_name='vehicles_1',
            new_name='vehicles_1_plus',
        ),
        migrations.RemoveField(
            model_name='unitdescription',
            name='vehicles_2_plus',
        ),
    ]
