# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0008_auto_20160419_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_school_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elem_school_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hs_school_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_life_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commute_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crime_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noise_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
